restylers:
  - clang-format:
      enabled: false
  - jq:
      enabled: false # prefer prettier-json
  - prettier:
      include:
        - "**/*.md"
        - "**/*.yml"
        - "**/*.yaml"
  - whitespace:
      include:
        - "**/*"
  - "*"
